### ISSUE TITLE
Avoid response body overhead

### ISSUE THREAD

**Issue by danleyb2** [alfiepoleon/kenya-news-scrapper#3]
https://github.com/alfiepoleon/kenya-news-scrapper/blob/d34c0f9a846c101862586d92be419df2e4e81635/scrape_web.py#L27-L27

i think, if you just checking the return status_code and connection availability, this is better suited

```py
    request = requests.head(url)
```

**Comment by alfiepoleon** [comment]
Yes, didn't know that could be done, I will update that ASAP.
http://docs.python-requests.org/en/master/api/#requests.get

**Comment by alfiepoleon** [comment]
Fixed
