### ISSUE TITLE
Add more Sources

### ISSUE THREAD

**Issue by danleyb2** [alfiepoleon/kenya-news-scrapper#5]
more sources more info
- [ ] http://www.mediamaxnetwork.co.ke/news/
- [ ] http://nairobinews.nation.co.ke/
- [ ] http://www.ghafla.com/ke/
- [ ] http://zipo.co.ke/

**Comment by alfiepoleon** [comment]
Are these the next 4 biggest news sources?

**Comment by danleyb2** [comment]
@alfiepoleon this are the ones i could find

**Comment by alfiepoleon** [comment]
I think I'll concentrate on other areas first, like sports, lifestyle,...
